GET http://localhost:8000/api/users/ HTTP/1.1

###

POST http://localhost:8000/api/users/validate HTTP/1.1
Content-Type: application/json

{
  "phone": "77086144670",
  "password": "awdawdawd"
}

###

PUT http://localhost:8000/api/users/update HTTP/1.1
Content-Type: application/json

{
  "id": 3,
  "name": "Test",
  "surname": "User",
  "phone": "77086144676"
}

###

DELETE http://localhost:8000/api/users/delete HTTP/1.1
Content-Type: application/json

{
  "id": 3
}

###

POST http://localhost:8000/api/users/create HTTP/1.1
Content-Type: application/json

{
  "name": "Test",
  "surname": "Test",
  "phone": "77086144676",
  "birthday": "12-12-2000",
  "gender": 1,
  "password": "awdawdawd"
}